name: Check Markdown and doc links

on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  link-checker:
    if: github.repository == 'SonySemiconductorSolutions/mct-model-optimization'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.*
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.27.1
      - name: Run unittests
        run: |
          export CURL_CA_BUNDLE=''
          python -m unittest tests/doc_tests/test_docs_links.py -v