name: Run PyTorch Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      torch-version:
        required: true
        type: string

jobs:
  run-pytorch-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          pip install torch==${{ inputs.torch-version }} torchvision onnx onnxruntime "onnxruntime-extensions<0.14"
          pip install pytest pytest-mock
          pip check
      - name: Run pytest
        run: |
          pytest tests_pytest/pytorch_tests -s
      - name: Run unittests
        run: |
          python -m unittest discover tests/pytorch_tests -v


