name: Python 3.10, Keras 2.14
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-tests:
    uses: ./.github/workflows/run_keras_tests.yml
    with:
      python-version: "3.10"
      tf-version: "2.14.*"