name: Run Common Tests
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    # Run common tests across Python 3.10, 3.11, and 3.12.
    # Verify PuLP 3.x compatibility on Python 3.10/3.11 and PuLP 4.x compatibility on Python 3.12.
    # Include NumPy regression tests, excluding NumPy 2.4 on Python 3.10.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
        np_ver: [ "<2.4", "2.4" ]
        exclude:
          - python-version: "3.10"
            np_ver: "2.4"  # Numpy 2.4 is not supported on Python 3.10
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          if [[ "${{ matrix.np_ver }}" == "<2.4" ]]; then
            pip install numpy 'numpy<2.4'
          fi
          pip install pytest pytest-mock
          pip list | grep -i -e numpy -e pulp
          pip check

      - name: Run unittests
        run: python -m unittest discover tests/common_tests -v

      - name: Run pytest
        run:  pytest tests_pytest/common_tests

